/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-PDFium.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : PDFium
 #	author : miyako
 #	2020/01/01
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-PDFium.h"

#pragma mark -

void OnStartup() {
        
    FPDF_InitLibrary();
}

void OnExit() {
    
    FPDF_DestroyLibrary();
}

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
            case kInitPlugin :
            case kServerInitPlugin :
                OnStartup();
                break;

            case kDeinitPlugin :
                OnExit();
                break;
                
			// --- PDFium
            
			case 1 :
				PDFium_Test(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void write_data_fn(png_structp png_ptr, png_bytep buf, png_size_t size) {
    C_BLOB *blob = (C_BLOB *)png_get_io_ptr(png_ptr);
    blob->addBytes((const uint8_t *)buf, (uint32_t)size);
}

#pragma mark -

void output_flush_fn(png_structp png_ptr)
{
    
}

#define INCHES_PER_METER (100.0/2.54)

PA_Picture CreatePng(const void *buffer_void,
                     int stride,
                     int width,
                     int height,
                     png_uint_32 dpi_x,
                     png_uint_32 dpi_y) {
    
    PA_Picture picture = NULL;
    
    const char *buffer = reinterpret_cast<const char *>(buffer_void);
    
    if (stride < 0 || width < 0 || height < 0)
        return picture;
    if (height > 0 && width > INT_MAX / height)
        return picture;
    int out_len = width * height;
    if (out_len > INT_MAX / 3)
        return picture;
    
    out_len *= 3;
    
    png_structp  png_ptr;
    png_infop  info_ptr;
    
    png_ptr = png_create_write_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
    if(png_ptr != NULL)
    {
        info_ptr = png_create_info_struct(png_ptr);
        if(info_ptr == NULL)
        {
            png_destroy_write_struct(&png_ptr, NULL);
        }else
        {
            if(setjmp(png_jmpbuf(png_ptr))) {
                png_destroy_write_struct(&png_ptr, &info_ptr);
            }else
            {
                
                C_BLOB png;
                
                int depth = 8;/*BitsPerPixel*/
                int color = PNG_COLOR_TYPE_RGB_ALPHA;
                
                png_set_write_fn(png_ptr, (png_voidp)&png, write_data_fn, output_flush_fn);
                
                png_set_IHDR(png_ptr, info_ptr,
                             width, //pixels_per_line
                             height,//lines
                             depth,
                             color,
                             PNG_INTERLACE_NONE,
                             PNG_COMPRESSION_TYPE_DEFAULT,
                             PNG_FILTER_TYPE_DEFAULT);
                
                png_set_pHYs(png_ptr, info_ptr,
                                         dpi_x * INCHES_PER_METER,
                                         dpi_y * INCHES_PER_METER,
                                         PNG_RESOLUTION_METER);
                
                png_write_info(png_ptr, info_ptr);
                
                std::vector<unsigned char>rgb(stride);
                
                time_t startTime = time(0);
                
                for(int y = 0; y < height; ++y) {
                    
                    time_t now = time(0);
                    time_t elapsedTime = abs(startTime - now);
                    
                    if(elapsedTime > 0)
                    {
                        startTime = now;
                        PA_YieldAbsolute();
                    }
                    
                    const char *p = buffer + (stride * y);
                    for (int x = 0; x < width; ++x) {
                        rgb[(x * 4)    ] = p[(x * 4) + 2];
                        rgb[(x * 4) + 1] = p[(x * 4) + 1];
                        rgb[(x * 4) + 2] = p[(x * 4)    ];
                        rgb[(x * 4) + 3] = p[(x * 4) + 3];
                    }
                    png_write_row(png_ptr, &rgb[0]);
                }//height
                
                png_set_compression_level(png_ptr, Z_BEST_COMPRESSION);
                
                png_write_end(png_ptr, info_ptr);
                
                picture = PA_CreatePicture((void*)png.getBytesPtr(), png.getBytesLength());
            }
            png_destroy_write_struct(&png_ptr, &info_ptr);
        }
    }
    
    return picture;
}

#pragma mark -

void PDFium_Test(PA_PluginParameters params) {

    PackagePtr pParams = (PackagePtr)params->fParameters;

    C_TEXT path;
    path.fromParamAtIndex(pParams, 1);
        
    PA_ObjectRef options = PA_GetObjectParameter(params, 2);
    PA_CollectionRef returnValue = PA_CreateCollection();
    
    CUTF8String u8;
    path.copyPath(&u8);
    
    FPDF_BYTESTRING password = NULL;
    
    int flags = 0;
    int rotate = 0;
    double scale = 1.0;
    
    png_uint_32 dpi = 96;
    
    if(options) {
        
        if(ob_is_defined(options, L"password")) {
            CUTF8String u8password;
            ob_get_s(options, L"password", &u8password);
            password = (const char *)u8password.c_str();
        }
        
        if(ob_is_defined(options, L"rotate")) {
            rotate = ob_get_n(options, L"rotate");
        }
        
        if(ob_is_defined(options, L"scale")) {
            scale = ob_get_n(options, L"scale");
        }

        if(ob_is_defined(options, L"dpi")) {
            dpi = ob_get_n(options, L"dpi");
        }
        
        if(ob_get_b(options, L"FPDF_ANNOT")) {
            flags = flags|FPDF_ANNOT;
        }
        
        if(ob_get_b(options, L"FPDF_LCD_TEXT")) {
            flags = flags|FPDF_LCD_TEXT;
        }

        if(ob_get_b(options, L"FPDF_NO_NATIVETEXT")) {
            flags = flags|FPDF_NO_NATIVETEXT;
        }

        if(ob_get_b(options, L"FPDF_GRAYSCALE")) {
            flags = flags|FPDF_GRAYSCALE;
        }
        
        if(ob_get_b(options, L"FPDF_RENDER_LIMITEDIMAGECACHE")) {
            flags = flags|FPDF_RENDER_LIMITEDIMAGECACHE;
        }
        
        if(ob_get_b(options, L"FPDF_RENDER_FORCEHALFTONE")) {
            flags = flags|FPDF_RENDER_FORCEHALFTONE;
        }

        if(ob_get_b(options, L"FPDF_PRINTING")) {
            flags = flags|FPDF_PRINTING;
        }

        if(ob_get_b(options, L"FPDF_RENDER_NO_SMOOTHTEXT")) {
            flags = flags|FPDF_RENDER_NO_SMOOTHTEXT;
        }

        if(ob_get_b(options, L"FPDF_RENDER_NO_SMOOTHIMAGE")) {
            flags = flags|FPDF_RENDER_NO_SMOOTHIMAGE;
        }
        
        if(ob_get_b(options, L"FPDF_RENDER_NO_SMOOTHPATH")) {
            flags = flags|FPDF_RENDER_NO_SMOOTHPATH;
        }
        
    }
    
    FPDF_STRING docPath = (const char *)u8.c_str();
    
    if(docPath) {
        FPDF_DOCUMENT doc = FPDF_LoadDocument(docPath, password);
        int page_count = FPDF_GetPageCount(doc);
        
        for (int i = 0; i < page_count; ++i) {
            FPDF_PAGE page = FPDF_LoadPage(doc, i);
            
            if (!page) {
                PA_Variable va_null = PA_CreateVariable(eVK_Null);
                PA_SetCollectionElement(returnValue, i, va_null);
                PA_ClearVariable(&va_null);
                continue;
            }
                        
            int height = static_cast<int>(FPDF_GetPageHeight(page));
            int width = static_cast<int>(FPDF_GetPageWidth(page));
            
            height = height * scale;
            width = width * scale;
            
            FPDF_BITMAP bitmap = FPDFBitmap_Create(width,
                                                   height,
                                                   1);
            FPDFBitmap_FillRect(bitmap, 0, 0,
                                width,
                                height,
                                0x00000000);
            
            FPDF_RenderPageBitmap(bitmap, page, 0, 0,
                                  width,
                                  height,
                                  rotate, flags);

            const char *buffer = reinterpret_cast<const char*>(FPDFBitmap_GetBuffer(bitmap));
               
            PA_Variable va_picture = PA_CreateVariable(eVK_Picture);
            PA_SetPictureVariable(&va_picture, CreatePng(buffer,
                                                         FPDFBitmap_GetStride(bitmap),
                                                         width,
                                                         height,
                                                         dpi,
                                                         dpi));
            PA_SetCollectionElement(returnValue, i, va_picture);
            PA_ClearVariable(&va_picture);
            
            FPDFBitmap_Destroy(bitmap);
            FPDF_ClosePage(page);
            
        }

        FPDF_CloseDocument(doc);
    }
    
    PA_ReturnCollection(params, returnValue);
}
