/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-PDFium.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDFium
 #	author : miyako
 #	2020/01/01
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PDFIUM_H
#define PLUGIN_PDFIUM_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#include "C_BLOB.h"
#include "C_TEXT.h"

#include <fpdfview.h>

#include <libpng16/png.h>
#if VERSIONMAC
#include <zlib.h>
#else
#include <zlib/zlib.h>
#endif

#pragma mark -

void PDFium_Test(PA_PluginParameters params);

#endif /* PLUGIN_PDFIUM_H */
