/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-pdfium.h
 #	source generated by 4D Plugin Wizard
 #	Project : pdfium
 #	author : miyako
 #	2025/06/17
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PDFIUM_H
#define PLUGIN_PDFIUM_H

#include "4DPluginAPI.h"
#include <string>
#include "C_TEXT.h"
#include "4DPlugin-JSON.h"
#include <chrono>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

#include <fpdfview.h>
#include <fpdf_save.h>
#include <fpdf_doc.h>
#include <fpdf_text.h>
#include <fpdf_annot.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>

#pragma mark -

void pdf_to_image(PA_PluginParameters params);

#endif /* PLUGIN_PDFIUM_H */
